services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
